version: "3"
services:
  database:
    image: "postgres:16.1"
    container_name: "risks-database"
    environment:
      - POSTGRES_PASSWORD=risk
      - POSTGRES_USER=risk
      - POSTGRES_DB=risk_rules_database
    ports:
      - "5432:5432"

